import type { VocabItem } from './types'

export const fandomNames: VocabItem[] = [
  { korean: '엔진', romanji: 'ENGENE', japanese: 'ENHYPENのファンダム名' },
  { korean: '제로즈', romanji: 'ZEROSE', japanese: 'ZEROBASEONEのファンダム名' },
  { korean: '42', romanji: 'Forty Two', japanese: 'TWSのファンダム名' },
  { korean: '원도어', romanji: 'ONE DOOR', japanese: 'BOYNEXT DOORのファンダム名' },
]

export const fandomVocab: VocabItem[] = [
  ...fandomNames,
  { korean: '팬클럽', romanji: 'paen-keullop', japanese: 'ファンクラブ' },
  { korean: '팬미팅', romanji: 'paen-miting', japanese: 'ファンミーティング' },
  { korean: '컴백', romanji: 'keombaek', japanese: 'カムバック' },
  { korean: '뮤직비디오', romanji: 'myujik-bidio', japanese: 'ミュージックビデオ' },
  { korean: '음방', romanji: 'eumbang', japanese: '音楽番組' },
  { korean: '1위', romanji: 'irwi', japanese: '1位' },
  { korean: '쇼케이스', romanji: 'syokeis-eu', japanese: 'ショーケース' },
  { korean: '콘서트', romanji: 'konseoteu', japanese: 'コンサート' },
  { korean: '위버스', romanji: 'wiboseu', japanese: 'Weverse' },
  { korean: '버블', romanji: 'beobeul', japanese: 'Bubble' },
  { korean: '직관', romanji: 'jikgwan', japanese: '現場観戦' },
  { korean: '굿즈', romanji: 'gutseu', japanese: 'グッズ' },
  { korean: '앨범', romanji: 'aelbom', japanese: 'アルバム' },
  { korean: '응원봉', romanji: 'eungwonbong', japanese: 'ペンライト' },
  { korean: '팬사인회', romanji: 'paen-sainhwe', japanese: 'ファンサイン会' },
  { korean: '챔피언십', romanji: 'chaempieon-sip', japanese: '音楽番組1位' },
  { korean: '데뷔', romanji: 'debwi', japanese: 'デビュー' },
  { korean: '솔로', romanji: 'sollo', japanese: 'ソロ' },
  { korean: '유닛', romanji: 'yunit', japanese: 'ユニット' },
  { korean: '월드투어', romanji: 'woldeu-tueo', japanese: 'ワールドツアー' },
  { korean: '스케줄', romanji: 'seukejul', japanese: 'スケジュール' },
  { korean: '티저', romanji: 'tijeo', japanese: 'ティーザー' },
  { korean: '엠카운트다운', romanji: 'em-kaunteudown', japanese: 'M COUNTDOWN（音楽番組）' },
  { korean: '뮤직뱅크', romanji: 'myujik-baengkeu', japanese: 'Music Bank（音楽番組）' },
  { korean: '인기가요', romanji: 'ingigayo', japanese: 'Inkigayo（音楽番組）' },
  { korean: '쇼챔피언', romanji: 'syo-chaempieon', japanese: 'Show Champion（音楽番組）' },
  { korean: '스트리밍', romanji: 'seuteuriming', japanese: 'ストリーミング' },
  { korean: '팬덤', romanji: 'paendeom', japanese: 'ファンダム' },
  { korean: '대기실', romanji: 'daegisil', japanese: '楽屋' },
  { korean: '리허설', romanji: 'riheoseol', japanese: 'リハーサル' },
  { korean: '본방사수', romanji: 'bonbang-sasu', japanese: 'リアタイ視聴（生放送を必ず見ること）' },
  { korean: '음원', romanji: 'eumwon', japanese: '音源' },
  { korean: '뮤비', romanji: 'myubi', japanese: 'MV（ミュージックビデオの略）' },
  { korean: '자켓', romanji: 'jaket', japanese: 'ジャケット写真' },
  { korean: '클립', romanji: 'keullip', japanese: 'クリップ映像' },
]
