import type { VocabItem } from './types'

export const oshikatsuVocab: VocabItem[] = [
  { korean: '덕질', romanji: 'deokjil', japanese: '推し活' },
  { korean: '최애', romanji: 'choeae', japanese: '最推し' },
  { korean: '차애', romanji: 'chaae', japanese: '二番推し' },
  { korean: '직캠', romanji: 'jikkaem', japanese: '直カム / fancam' },
  { korean: '포카', romanji: 'poka', japanese: 'フォトカード' },
  { korean: '포카 교환', romanji: 'poka gyohwan', japanese: 'フォトカード交換' },
  { korean: '팬아트', romanji: 'paen-ateu', japanese: 'ファンアート' },
  { korean: '팬편지', romanji: 'paen-pyeonji', japanese: 'ファンレター' },
  { korean: '공구', romanji: 'gonggu', japanese: '共同購入' },
  { korean: '조공', romanji: 'jogong', japanese: 'アイドルへの貢ぎ物' },
  { korean: '생일카페', romanji: 'saengil-kape', japanese: 'バースデーカフェ' },
  { korean: '스밍', romanji: 'seuming', japanese: 'ストリーミング' },
  { korean: '총공', romanji: 'chonggong', japanese: '総攻撃（一斉ストリーミング）' },
  { korean: '입덕', romanji: 'ipdeok', japanese: '沼落ち' },
  { korean: '탈덕', romanji: 'taldeok', japanese: '沼抜け' },
  { korean: '사진', romanji: 'sajin', japanese: '写真' },
  { korean: '직찍', romanji: 'jikjjik', japanese: '直撮り写真' },
  { korean: '홈마', romanji: 'homma', japanese: 'ホームマスター（応援カメラマン）' },
  { korean: '오빠', romanji: 'oppa', japanese: 'お兄さん（ファンが男性アイドルに呼ぶ）' },
  { korean: '언니', romanji: 'eonni', japanese: 'お姉さん' },
  { korean: '남친짤', romanji: 'namchin-jjal', japanese: '彼氏っぽい写真' },
  { korean: '심쿵', romanji: 'simkung', japanese: '胸キュン' },
  { korean: '사인회', romanji: 'sainhwe', japanese: 'サイン会' },
  { korean: '팬카페', romanji: 'paen-kape', japanese: 'ファンカフェ' },
  { korean: '공방', romanji: 'gongbang', japanese: '公放（生放送スタジオ観覧）' },
  { korean: '입덕계기', romanji: 'ipdeok-gyegi', japanese: '沼落ちのきっかけ' },
  { korean: '최애픽', romanji: 'choeae-pik', japanese: '最推しピック' },
  { korean: '셀카', romanji: 'selka', japanese: '自撮り写真' },
  { korean: '브이로그', romanji: 'beu-i-rogeu', japanese: 'Vlog' },
  { korean: '개인 방송', romanji: 'gaein bangsong', japanese: '個人配信' },
  { korean: '팔로우', romanji: 'pallou', japanese: 'フォロー' },
  { korean: '리트윗', romanji: 'riteuwiit', japanese: 'リツイート' },
  { korean: '팬페이지', romanji: 'paen-peiji', japanese: 'ファンページ' },
  { korean: '응원법', romanji: 'eungwonbeop', japanese: '応援の掛け声' },
  { korean: '야광봉', romanji: 'yagwangbong', japanese: 'ペンライト' },
]
